config/routes.rb
Rails.application.routes.draw do
  # this means when we receive a GET request with `/` url we invoke the index
  # action within the Home Controller
  root 'home#index'

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection #if it's 'on collection', it skips having an id of any sort in the URL, for security, we can destroy session like this 
  end

  #the url helpers, when we set them using 'as' , are only concerned about the
  #URL and not the CERB , so even if we have two routes with the same URL and
  #different verbs, the url helper
  # should be the same
  # get({'/questions/new' => 'questions#new', as: :new_question})
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get 'questions'       => 'questions#index'
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update' #questions/:id is alrady there so you don't need to specify an 'as: '
  # delete '/questions/:id' => 'questions#destroy' #as not needed , already defined
  #
resources :questions, shallow: true do
  get :search, on: :collection
  get :flag, on: :member
  post :approve
  # nesting the answers resources within the questions resources block
# will make it so that every `answers` route is prefixed with:
# `/questions/:question_id`. We will need the `question_id` to create
# an answer associated with a question so we will stick with this way of
# defining the routes. The routes helpers will also have `question_` prefix
  resources :answers, on: [:create, :destroy]do
      resources :comments, only: [:create, :destroy]
    end
end


  get '/contact' => 'home#contact' # Rails auto-generate a URL helper called
                                   # contact_path (and contact_url)

  post '/contact_submit' => 'home#contact_submit'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  has_many :answers, lambda { order(created_at: :DESC) }, dependent: :destroy

  validates :title, presence: true,
  uniqueness: { case_sensitive: false,
  message: "must be unique"}

#with scope we valudate that the combination of two fields is unique. In the example below
#we are validating that the combination of title/body is unique.

  validates :body, length: {minimum: 5},
            uniqueness: {scope: :title}

  # validates :view_count, numericality: {greater_than_or_equal_to: 0}
# This is the more verbose form of doing validation , to show classes
  validates(:view_count, { numericality: {greater_than_or_equal_to: 0} } )

# assign a private method for something obscure like 'no monkey'
  validate :no_monkey

#callback methods:
  after_initialize :set_defaults
  before_validation :titleize_title

# scope :recent_ten, lambda { limit(10).order(created_at: :desc)}
#
  def self.recent_ten
    Question.limit(10).order(created_at: :desc)
  end

  def user_full_name
    if user
      user.full_name
    else
      'Anonymous'
    end
  end


  private

  def no_monkey
# add an error on the title field
    if title && title.include?('monkey')
      errors.add(:title, 'No monkeys please!')
    end
  end

  def set_defaults #if you wanna set something in ruby , you have instance variables @viewcount - something , or the other option , if you have attr accessor , you can self.viewcount , that value to something
    #if you wanna set the value of a
    self.view_count ||= 0
  end

  def titleize_title
    self.title = title.titleize
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # this action is to show the form for creating a new question
  # the URL: /questions/new
  # the path helper is: new_question_path
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_question, only: [:edit, :update, :destroy, :show]


  #the before action methods will be executed at the order they are defined.
  # This means the 'quthenticate_user' will be caled beore the 'authorize_access' method. This means that the user will be authenticated when we're inside the ''authorize_access' method so we don't have to check for that.
  before_action :authorize_access, only: [:edit, :update, :destroy]
  #before_action (:find_question, {only: [:edit, :update, :destroy, :show]})
  #the 'before_action' method in here registers a method (usually private)
  #to be executed just before controller actions. this happens within the same
  #request response cycle, which means if you define an instance variable
  #it will be available within the action
  #You can optionally give options: 'only' or 'except' to restrict the actions
  #that this 'before_action' method applies to.
  # Another way of writing it that is less explicit but viable:
  # before_action :find_question, except: [:index, :new, :create]

  def new
    @question = Question.new
  end

  # this action is to handle creating a new question after submitting the form
  # that was shown in the new action
  def create

    #flash works very similar to the session in a sense that it uses cookies
    #to store values that persist through redirect_to or render
    # flash will clear the value as soon as it's read so it doesn't persist
    #through the rest of the requests
    #session[:notice] = 'Question Created!'
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      # redirect_to question_path({id: @question.id})
      # redirect_to question_path({id: @question})
      flash[:notice] = 'Question Created!'
      redirect_to question_path(@question)
    else
      flash.now[:alert] = 'Please see errors below'
      # if we juse use flash[:alert] in here then the flash message will persist
      # to the next request as well. flash.now[:alert] will make it only show
      # when you render the `:new` template but it won't persist to the next
      # request
      render :new
    end
  end

#this action is to show information about a specific information
#URL: /questions/ :id (for example /questions/123)
#METHOD " GET"


  def show
    # render plain: "In show action"
    @answer = Answer.new
  end


#this action is to show a listings of all the questions
#URL :/questions
#METHOD: GET
  def index
    @questions = Question.order(created_at: :desc).limit(10).offset(10) #give it an instance variable if you wanna share it with a view , and pluralize it because there will be many questions
  end
  #this action is to show a form pre-population with the question's data
  #URL: /questions/:id/edit
  #METHOD : GET
  def edit
    @question = Question.find params[:id]
    #every action is independent of any other action. This page is full of actions.
  end

  #this action is to capture the params from the form submission form the edit
  #action in order to update a questions
  #URL :/questions/:id
  #METHOD: PATCH
  def update
      # when searching for question params it will go one step higher , from inside method , to inside class
      if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end



  #this action handles deleting a question
  #URL :/questions/:id
  #METHOD: DELETE
  def destroy
    @question.destroy
    # adding 'notice: 'Question deleted' to the redirect_to line will set a
    #flash notice message as we did the create / update actions notice that this #only works for redirect and not for render
    redirect_to questions_path, notice: 'Question deleted'
  end

private

  def question_params
    params.require(:question).permit([:title, :body])
  end

  def find_question
    @question = Question.find params[:id]
  end

  def authorize_access
    unless can? :manage, @question
      # head :unauthorized #this will send an empty HTTP response with 401 code
      redirect_to root_path, alert: 'access denied'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join(', ') %>

<%# We use form_for when we're creating a form related to a Rails model. the
    first argument of the form_for must be an ActiveRecord object.
    if the first argument is a new instance of the ActiveRecord class, for
    example, Question.new then the form will automatically send a POST request
    to the standard create action url which is in this case: questions_path %>
<%= form_for @question do |f| %>
  <div>
    <%# we can use f.label and f.text_field to generate a label/text input group
        in this case `title` must be an attribute for the variable you pass to
        form_for which is @question in this case.
        The label will have a`for` attribute that matches the id of the
        generated input field for the title.
        The title input field will have a name attribute that is model_type[field]
        In the example below the `name` attribute for the input field will be:
        question[title].
        The input field will be prepolulated with a value if the @question
        has that attribute value set to something. %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%# this will automatically generate a submit button. The label for the button
      will depend on the `@question` variable. If @question is a new instance
      then the label of the button will be `Create #{model name capitalized}`.
      If you're not happy with the label, you can pass the label as a first
      arguement: f.submit 'Create'  %>
  <%= f.submit btn_label %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form', {btn_label: 'Update'} %>

<%# if the object you pass to the  form_for is persisted (has an id in the DB) then rails will automatically make the form submit a PATCH request with URL in this case question_path (@question ) (same as show link with PATCH request).
@question variable is persisted in this case so it will have a title and a body so those will be pre-populated in the respective field %>

  <%# this will automatically generate a submit button. The label for the button
      will depend on the `@question` variable. If @question is a new instance
      then the label of the button will be `Create #{model name capitalized}`.
      If you're not happy with the label, you can pass the label as a first
      arguement: f.submit 'Create'  %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<!-- Give it a default view -->
<% @questions.each do |q| %>
<%= link_to q.title, question_path(q.id) %>
<hr>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%# we moved the form_for into a separate file  %>
<%# calling it back using a helper method called 'render' %>
<%# render '/questions/form'      <<<<<< more verbose way of putting it but they are in the same folder so a partial path is fine , and it will render the form%>
<%# Partials have access to the same instance variable as the template they ar rendered within. IOn this case the _form partial will have access to @question variable.  %>
<%= render 'form', {btn_label: 'Submit'} %>
<%# In this case there will be a local variable named 'btn_label' within the _form.html.erb partial and it will have the value of 'Submit' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%# questions_answers_path(@question) %>
<p><%= @question.body %></p>

<p>
  Created by: <%= @question.user_full_name %>
</p>

<% if can? :manage, @question %>
<%= link_to 'edit', edit_question_path(@question) %>
<%= link_to 'delete', question_path(@question),
                      method: :delete,
                      data: { confirm: 'Are you sure?'} %>
<% end %>
<%# form_for @answer, url: question_answers_path(@question)  do |f| %>
<%= @answer.errors.full_messages.join(', ') %>
<%= form_for [@question, @answer] do |f| %>
<div class="">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %>

<h2>All Answers</h2>
<% @question.answers.each do |answer| %>
    User: <%= answer.user.first_name %> |
    Answer: <%= answer.body %> |
    <%  if can? :delete, answer %>
<%= link_to 'delete', answer_path(answer),
                      method: :delete,
                      data: { confirm: 'are you sure?'} %>

<hr>
<% end %>
<% end %>