config/routes.rb
Rails.application.routes.draw do
  # this means when we receive a GET request with `/` url we invoke the index
  # action within the Home Controller
  root 'home#index'

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection #if it's 'on collection', it skips having an id of any sort in the URL, for security, we can destroy session like this 
  end

  #the url helpers, when we set them using 'as' , are only concerned about the
  #URL and not the CERB , so even if we have two routes with the same URL and
  #different verbs, the url helper
  # should be the same
  # get({'/questions/new' => 'questions#new', as: :new_question})
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get 'questions'       => 'questions#index'
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update' #questions/:id is alrady there so you don't need to specify an 'as: '
  # delete '/questions/:id' => 'questions#destroy' #as not needed , already defined
  #
resources :questions, shallow: true do
  get :search, on: :collection
  get :flag, on: :member
  post :approve
  # nesting the answers resources within the questions resources block
# will make it so that every `answers` route is prefixed with:
# `/questions/:question_id`. We will need the `question_id` to create
# an answer associated with a question so we will stick with this way of
# defining the routes. The routes helpers will also have `question_` prefix
  resources :answers, on: [:create, :destroy]do
      resources :comments, only: [:create, :destroy]
    end
end


  get '/contact' => 'home#contact' # Rails auto-generate a URL helper called
                                   # contact_path (and contact_url)

  post '/contact_submit' => 'home#contact_submit'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #this method is called 'action'
  def index
    #this will render views/homes/index.html.erb and it will Use
    #views/layours/application.html.erb
    #
    # render :index, layout: 'application'
    #rails automatically renders the layout from the appropriate irectory
    #rails takes the second format as the argument ,  in index.html.erb
  end

  def contact
    #if you wanna do something different, you can write
    #index: something else
  end

  def contact_submit
    @name = params[:full_name]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<h1>Contact Us</h1>
<h1>This is blowing my mind right now</h1>
<%# form_tag is a helper method that will generate a form HTML element with POST httml request. The first
argument of the helper method  must be the URL you would like to submit the form to. %>
<%= form_tag contact_submit_path do %>
<div class="">
    <%= label_tag :full_name %>
    <%= text_field_tag :full_name %>
</div>
<div class="">
    <%= label_tag :email %>
    <%= email_field_tag :email %>
</div>
<div class="">
    <%= label_tag :message %>
    <%= text_area_tag  :message %>
</div>
  <%= submit_tag "Contact Us!" %>
<% end %>

app/views/home/contact_submit.html.erb
<h1>Thanks <%= @name %>for contacting us</h1>

app/views/home/index.html.erb
<h1>Welcome to Awesome Answers</h1>
<%= image_tag 'http://a3.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,q_80,w_620/MTIwNjA4NjMzOTUyMjQxMTY0.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>
<%= image_tag 'django.jpg' %>