config/routes.rb
Rails.application.routes.draw do
  # this means when we receive a GET request with `/` url we invoke the index
  # action within the Home Controller
  root 'home#index'

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection #if it's 'on collection', it skips having an id of any sort in the URL, for security, we can destroy session like this 
  end

  #the url helpers, when we set them using 'as' , are only concerned about the
  #URL and not the CERB , so even if we have two routes with the same URL and
  #different verbs, the url helper
  # should be the same
  # get({'/questions/new' => 'questions#new', as: :new_question})
  # post({'/questions'    => 'questions#create', as: :questions})
  # get '/questions/:id'  => 'questions#show', as: :question
  # get 'questions'       => 'questions#index'
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  # patch '/questions/:id' => 'questions#update' #questions/:id is alrady there so you don't need to specify an 'as: '
  # delete '/questions/:id' => 'questions#destroy' #as not needed , already defined
  #
resources :questions, shallow: true do
  get :search, on: :collection
  get :flag, on: :member
  post :approve
  # nesting the answers resources within the questions resources block
# will make it so that every `answers` route is prefixed with:
# `/questions/:question_id`. We will need the `question_id` to create
# an answer associated with a question so we will stick with this way of
# defining the routes. The routes helpers will also have `question_` prefix
  resources :answers, on: [:create, :destroy]do
      resources :comments, only: [:create, :destroy]
    end
end


  get '/contact' => 'home#contact' # Rails auto-generate a URL helper called
                                   # contact_path (and contact_url)

  post '/contact_submit' => 'home#contact_submit'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>

    <%# this refers to the application.css manifest file , so in development it will include all the files individual css files. In production it will only incldue the application.css compiled file.  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body background="http://www.planwallpaper.com/static/images/cool-background.jpg">

    <!-- <a href='/'>Home</a> -->
    <%= link_to 'Home', root_path %>
    |
    <!-- <a href='/contact'>Contact Us</a> -->
    <%#= link_to 'Contact Us', contact_path({something: 'hello world'}) %>
    <%= link_to 'Contact Us', contact_url %>
    |
    <%= link_to 'All Questions', questions_path %>
    |
    <%= link_to 'New Question', new_question_path %>
    <% if user_signed_in? %>
      Hello <%= current_user.first_name %>
      <%= link_to 'Sign out', sessions_path, method: :delete %>
    <% else %>|
      <%= link_to 'Sign Up', new_user_path %> |
      <%= link_to 'Sign In', new_session_path %> |
    <% end %>
    <hr>
    <%= flash[:notice] || flash[:alert]%>
    <%# notice || alert <<< another notation for above  %>
    <%# reason to use notice or alert is so that you can style them individually  %>
    <%= yield %>
  </body>
</html>